### ISSUE TITLE
上下班时间在哪设置的？

### ISSUE THREAD

**Issue by hylsay** [kakasearch/ding-punch#1]
上下班时间在哪设置的？

**Comment by kakasearch** [comment]
1、可以用autojs设置定时任务，到上下班的时候运行脚本，方法为：导入脚本后，点击main.js旁边的三点，点击设置任务，按照需求设置好脚本执行时间即可；
2、通过tasker定时执行脚本，方法：在任务编辑页面，点击+，点击插件，选择autojs，选择本脚本，然后在配置文件页面新建定时任务即可。

**Comment by hylsay** [comment]
谢谢，tasker已经弃用了，不稳定

**Comment by hylsay** [comment]
还有一个问题，我设置了定时任务，为什么无法唤醒屏幕？

**Comment by kakasearch** [comment]
> 还有一个问题，我设置了定时任务，为什么无法唤醒屏幕？

autojs自带的定时任务并不能按时准确执行，会有5-30min延迟，反而我用tasker能准确按时执行。
你可以在代码第一行处添加`sleep(5000);`，开始执行脚本后立刻关闭手机屏幕，检查是否能够唤醒屏幕。若依然不能唤醒，则是脚本的问题，可以尝试用其它方式唤醒屏幕后再执行脚本。
